steps:
  - name: "gcr.io/cloud-builders/docker"
    secretEnv: ["MICROCMS_API_KEY", "MICROCMS_SERVICE_DOMAIN"]
    entrypoint: "bash"
    args:
      [
        "-c",
        'docker build --build-arg MICROCMS_API_KEY="$$MICROCMS_API_KEY" --build-arg MICROCMS_SERVICE_DOMAIN="$$MICROCMS_SERVICE_DOMAIN" -t asia-northeast1-docker.pkg.dev/$PROJECT_ID/docker/ryokosuge-com:$COMMIT_SHA .',
      ]
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "asia-northeast1-docker.pkg.dev/$PROJECT_ID/docker/ryokosuge-com:$COMMIT_SHA",
      ]
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      - "run"
      - "deploy"
      - "ryokosuge-com"
      - "--image"
      - "asia-northeast1-docker.pkg.dev/$PROJECT_ID/docker/ryokosuge-com:$COMMIT_SHA"
      - "--region"
      - "asia-northeast1"

images:
  - asia-northeast1-docker.pkg.dev/$PROJECT_ID/docker/ryokosuge-com:$COMMIT_SHA

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_NUMBER/secrets/MICROCMS_API_KEY/versions/1
      env: MICROCMS_API_KEY
    - versionName: projects/$PROJECT_NUMBER/secrets/MICROCMS_SERVICE_DOMAIN/versions/1
      env: MICROCMS_SERVICE_DOMAIN

timeout: 500s
options:
  logging: CLOUD_LOGGING_ONLY
