name: Deploy to Cloud Run on schedule
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    env:
      DOCKER_IMAGE_NAME: ${{ secrets.GCP_ARTIFACT_REGISTRY_NAME }}/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.GCP_ARTIFACT_REGISTRY_REPOSITORY_NAME }}/${{ secrets.GCP_ARTIFACT_IMAGE_NAME }}:${{ github.sha }}
    steps:
      - uses: actions/checkout@v4
      - uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT_NAME }}
      - uses: "google-github-actions/setup-gcloud@v1"
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
      - run: gcloud auth configure-docker ${{ secrets.GCP_ARTIFACT_REGISTRY_NAME }}
      - run: docker build --build-arg MICROCMS_API_KEY=${{ secrets.MICROCMS_API_KEY }} --build-arg MICROCMS_SERVICE_DOMAIN=${{ secrets.MICROCMS_SERVICE_DOMAIN }} -t ${{ env.DOCKER_IMAGE_NAME }} .
      - run: docker push ${{ env.DOCKER_IMAGE_NAME }}
      - id: deploy-cloudrun
        uses: "google-github-actions/deploy-cloudrun@v1"
        with:
          service: ${{ secrets.GCP_CLOUDRUN_SERVICE_NAME }}
          image: ${{ env.DOCKER_IMAGE_NAME }}
          region: ${{ secrets.GCP_PROJECT_REGION }}
      - run: gcloud run services update-traffic ${{ secrets.GCP_CLOUDRUN_SERVICE_NAME }} --to-latest --region ${{ secrets.GCP_PROJECT_REGION }}
