name: PR

on:
  pull_request:
    branches:
      - main

env:
  UBUNTU_VERSION: ubuntu-22.04
  NODE_VERSION: 16

jobs:
  build:
    runs-on: ${{ env.UBUNTU_VERSION }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: yarn
      - run: yarn build
